apiVersion: v1
kind: Service
metadata:
  name: flask-basic-app
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: flask-basic-app
  ports:
    - protocol: TCP
      port: 80 # external port on the ELB
      targetPort: 5007 # container port
