apiVersion: v1
kind: Service
metadata:
  name: nextjs-app
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80 # external port on the ELB
      targetPort: 3000 # container port
